objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Payment_Date__c</fullName>
        <description>Date of the last payment made</description>
        <inlineHelpText>Date of the last payment made</inlineHelpText>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Payments_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total amount of all payments made</description>
        <inlineHelpText>Total amount of all payments made</inlineHelpText>
        <label>Total Payments Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Payment__c.object
<CustomObject>
    <description>Payments made by a person (Contact) to a Project.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of payment being made.</description>
        <inlineHelpText>Amount of payment being made.</inlineHelpText>
        <label>Amount</label>
        <precision>9</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Person making this payment.</description>
        <inlineHelpText>Person making this payment.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date the payment is made.</description>
        <inlineHelpText>Date the payment is made.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Project this payment is being made to.</description>
        <inlineHelpText>Project this payment is being made to.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PYMT-{00000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Projects to make payments to.</description>
    <fields>
        <fullName>Project_Name__c</fullName>
        <description>Name of project.</description>
        <inlineHelpText>Name of project.</inlineHelpText>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Payments_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total of all payments made to this project.</description>
        <inlineHelpText>Total of all payments made to this project.</inlineHelpText>
        <label>Total Payments Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PROJ-{00000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PaymentTriggerTest.cls
@isTest
private class PaymentTriggerTest {
    @isTest static void TestPaymentInsert() {
        // Test data setup
        Contact contact = new Contact(LastName='Test Payer LastName');
        insert contact;
        
        Project__c project = new Project__c(Project_Name__c='Test Project',
                                            Total_Payments_Amount__c = 3);
        insert project;
        
        Date todayDate = date.today();
        Payment__c payment = new Payment__c();
        payment.Amount__c = 1;
        payment.Contact__c = contact.Id;
        payment.Date__c = todayDate;
        payment.Project__c = project.id;
        
        
        // Test payment insert
        Test.startTest();
        Database.SaveResult result = Database.insert(payment, false);
        Test.stopTest();
        // Verify
        System.assert(result.isSuccess());
        System.assert(result.getErrors().size() == 0);
        System.assert([SELECT Last_Payment_Date__c FROM Contact].Last_Payment_Date__c == todayDate);
    }
    
    
    
    @isTest static void TestPaymentUpdate() {
        // Test data setup
        Contact contact = new Contact(LastName='Test Payer LastName');
        insert contact;
        
        Project__c project = new Project__c(Project_Name__c='Test Project',
                                            Total_Payments_Amount__c = 3);
        insert project;
        
        Date todayDate = date.today();
        Payment__c payment = new Payment__c();
        payment.Amount__c = 1;
        payment.Contact__c = contact.Id;
        payment.Date__c = todayDate;
        payment.Project__c = project.id;
        
        insert payment;
        
        System.debug(LoggingLevel.ERROR, 'Last_Payment_Date__c(should be 4): ' + [SELECT Total_Payments_Amount__c FROM Project__c].Total_Payments_Amount__c );

        // Test payment update
        payment.Amount__c = 10;
        Test.startTest();
        Database.SaveResult result = Database.update(payment, false);
        Test.stopTest();
        // Verify
        System.assert(result.isSuccess());
        System.assert(result.getErrors().size() == 0);
        System.debug(LoggingLevel.ERROR, 'Last_Payment_Date__c: ' + [SELECT Total_Payments_Amount__c FROM Project__c].Total_Payments_Amount__c );
        System.assert([SELECT Total_Payments_Amount__c FROM Project__c].Total_Payments_Amount__c == 13);
    }
    
    @isTest static void TestPaymentDelete() {
        // Test data setup
        Contact contact = new Contact(LastName='Test Payer LastName');
        insert contact;
        
        Project__c project = new Project__c(Project_Name__c='Test Project',
                                            Total_Payments_Amount__c = 3);
        insert project;
        
        
        Payment__c payment = new Payment__c();
        payment.Amount__c = 1;
        payment.Contact__c = contact.Id;
        payment.Date__c = date.today();
        payment.Project__c = project.id;

        insert payment;
        
        // Perform test
        System.assert([SELECT Id FROM Payment__c].size() == 1);
        Test.startTest();
        Database.DeleteResult result = Database.delete(payment, false);
        Test.stopTest();
        // Verify
        //System.debug(LoggingLevel.ERROR, 'DML results: ' + result.getErrors());
        System.assert(result.isSuccess());
        System.assert(result.getErrors().size() == 0);
        System.assert([SELECT Id FROM Payment__c].size() == 0);
    }
    
}