objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Payment_Date__c</fullName>
        <description>Date of the last payment made</description>
        <inlineHelpText>Date of the last payment made</inlineHelpText>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Payments_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total amount of all payments made</description>
        <inlineHelpText>Total amount of all payments made</inlineHelpText>
        <label>Total Payments Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Payment__c.object
<CustomObject>
    <description>Payments made by a person (Contact) to a Project.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of payment being made.</description>
        <inlineHelpText>Amount of payment being made.</inlineHelpText>
        <label>Amount</label>
        <precision>9</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Person making this payment.</description>
        <inlineHelpText>Person making this payment.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date the payment is made.</description>
        <inlineHelpText>Date the payment is made.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Project this payment is being made to.</description>
        <inlineHelpText>Project this payment is being made to.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PYMT-{00000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Projects to make payments to.</description>
    <fields>
        <fullName>Project_Name__c</fullName>
        <description>Name of project.</description>
        <inlineHelpText>Name of project.</inlineHelpText>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Payments_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total of all payments made to this project.</description>
        <inlineHelpText>Total of all payments made to this project.</inlineHelpText>
        <label>Total Payments Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PROJ-{00000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PresenceProjectPaymentApxTest.cls
@isTest
private class PresenceProjectPaymentApxTest {
    @isTest static void TestPaymentGetPayments() {
        // Test data setup
        Contact contact = new Contact(LastName='Test Payer LastName');
        insert contact;
        
        Project__c project = new Project__c(Project_Name__c='Test Project',
                                            Total_Payments_Amount__c = 3);
        insert project;
        
        Date todayDate = date.today();
        Payment__c payment = new Payment__c();
        payment.Amount__c = 1;
        payment.Contact__c = contact.Id;
        payment.Date__c = todayDate;
        payment.Project__c = project.id;
        
        
        
        // Test payment insert
        Test.startTest();
        PresenceProjectPaymentApx.getPayments();
        insert payment;
        Test.stopTest();
        PresenceProjectPaymentApx.getPayments();
        // Verify
        System.assert([SELECT Last_Payment_Date__c FROM Contact].Last_Payment_Date__c == todayDate);
    }
    @isTest static void TestPaymentInsert() {
        // Test data setup
        Contact contact = new Contact(LastName='Test Payer LastName');
        insert contact;
        
        Project__c project = new Project__c(Project_Name__c='Test Project', Total_Payments_Amount__c = 3);
        insert project;
        
        
        Date todayDate = date.today();
        
        // Test payment insert
        Test.startTest();
        PresenceProjectPaymentApx.insertPayment(contact.Id, project.id, (todayDate+1).format(), '100.0');
        Test.stopTest();
        // Verify
        System.assert([SELECT Total_Payments_Amount__c FROM Project__c].Total_Payments_Amount__c ==  3 + 100);
    }
    @isTest static void TestPaymentUpdate() {
        // Test data setup
        Contact contact = new Contact(LastName='Test Payer LastName');
        insert contact;
        
        Project__c project = new Project__c(Project_Name__c='Test Project',
                                            Total_Payments_Amount__c = 3);
        insert project;
        
        Date todayDate = date.today();
        Payment__c payment = new Payment__c();
        payment.Amount__c = 1;
        payment.Contact__c = contact.Id;
        payment.Date__c = todayDate;
        payment.Project__c = project.id;
        
        insert payment;
        
        // Test payment insert
        Test.startTest();
        PresenceProjectPaymentApx.updatePayment(payment.Id, (todayDate+1).format(), 200.0);
        Test.stopTest();
        // Verify
        System.assert([SELECT Total_Payments_Amount__c FROM Project__c].Total_Payments_Amount__c == 3+1+(200-1));
    }
    @isTest static void TestPaymentDelete() {
        // Test data setup
        Contact contact = new Contact(LastName='Test Payer LastName');
        insert contact;
        
        Project__c project = new Project__c(Project_Name__c='Test Project',
                                            Total_Payments_Amount__c = 3);
        insert project;
        
        Date todayDate = date.today();
        Payment__c payment = new Payment__c();
        payment.Amount__c = 1;
        payment.Contact__c = contact.Id;
        payment.Date__c = todayDate;
        payment.Project__c = project.id;
        
        insert payment;
        
        // Test payment insert
        Test.startTest();
        PresenceProjectPaymentApx.deletePayment(payment.Id);
        Test.stopTest();
        // Verify
        System.assert([SELECT Total_Payments_Amount__c FROM Project__c].Total_Payments_Amount__c == 3+1-1);
    }
    @isTest static void TestExceptionHandling() {
        PresenceProjectPaymentApx.ProjectPayment pp = new PresenceProjectPaymentApx.ProjectPayment(true);    // isExceptionTest = true

        // Test payment insert
        Test.startTest();
        
        pp.initialize();
        pp.getPayments();
        pp.getPayment(null);
        pp.editPayment(null,null);
        pp.createPayment(null,null,null,null);
        pp.updatePayment(null);
        pp.insertPayment(null);
        pp.deletePayment(null);
        pp.validateSave();
        pp.validateDelete();
        pp.parsePayments();
        pp.convertMapToList();
        
        PresenceProjectPaymentApx.getPayments(true);
        PresenceProjectPaymentApx.insertPayment(null,null,null,null, true);
        PresenceProjectPaymentApx.updatePayment(null,null,null,true);
        PresenceProjectPaymentApx.deletePayment(null,true);

        Test.stopTest();
        // Verify
    }
    
    @isTest static void TestDmlError() {
        PresenceProjectPaymentApx.ProjectPayment pp = new PresenceProjectPaymentApx.ProjectPayment();    // isExceptionTest = false
        pp.initialize();
        // Test payment insert
        Test.startTest();
        
        pp.getPayment(null);
        pp.insertPayment(null);
        pp.insertPayment(new List<sobject>{new Account()} );
        pp.validateSave();
        
        pp.deletePayment(new List<string>{'12334'});
        pp.validateDelete();

        Test.stopTest();
        // Verify
    }
    
}